global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'student-backend'
    metrics_path: /health
    static_configs:
      - targets: ['backend:3000']   # backend service name in docker-compose
